SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PARALAR'

SELECT *
FROM INFORMATION_SCHEMA.VIEWS

SELECT *
FROM INFORMATION_SCHEMA.ROUTINES where ROUTINE_TYPE = 'PROCEDURE'


SELECT SPECIFIC_NAME
FROM INFORMATION_SCHEMA.ROUTINES where ROUTINE_TYPE = 'FUNCTION'


-----------------------------------------------------
SELECT *
  FROM sys.columns
 WHERE object_id = OBJECT_ID('dbo.AnahtarKelimeKategoriler')

 CREATE TABLE [dbo].[AnahtarKelimeKategoriler](
	[ParentId] [int] NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[KategoriAdi] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_AnahtarKelimeKategoriler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
